export type Language = 'en' | 'ru' | 'kk';

export type LanguageOption = {
  code: Language;
  label: string;
};

export const languageOptions: LanguageOption[] = [
  { code: 'en', label: 'English' },
  { code: 'ru', label: 'Русский' },
  { code: 'kk', label: 'Қазақша' },
];

export const languageNames: Record<Language, string> = {
  en: 'English',
  ru: 'Russian',
  kk: 'Kazakh',
};

export const uiText = {
  en: {
    buddyName: 'Jey',
    diaryName: 'Jey Diary',
    headline: 'A diary that listens back.',
    intro:
      'A child can write or record feelings, then choose what stays private and what may be shown to a parent.',
    mineMood: 'Keeping this private',
    moodMood: 'Sharing mood only',
    parentMood: 'Ready to share gently',
    welcome:
      'I am Jey. Tell me as much or as little as you want. You choose what stays only yours.',
    placeholder: 'Write what happened today, or record your voice.',
    diaryLabel: 'Diary message',
    conversationLabel: 'Diary conversation',
    onlyMine: 'Only mine',
    moodOnly: 'Share mood',
    parentOk: 'Can show parent',
    moodBadge: 'Mood shared',
    parentBadge: 'Parent ok',
    aiTakeaway: 'Ask Jey',
    aiTakeawayLoading: 'Jey is reading the day',
    aiTakeawayEmpty: 'Jey could not make a summary yet.',
    me: 'Me',
    thinking: 'Jey is thinking',
    send: 'Send',
    record: 'Record',
    stop: 'Stop',
    voiceReady: 'Voice note ready',
    voiceTranscriptHint: 'If no words appear here, type one short line before sending.',
    noRecording: 'Recording is not available in this browser.',
    micNeeded: 'Microphone permission is needed to record.',
    parentSignal: 'Parent signal',
    noHint:
      'No parent alert right now. Private entries stay private unless the child chooses otherwise.',
    voiceEntry: 'I saved a voice note about my day.',
    albumsButton: 'Daily albums',
    registerButton: 'Register',
    albumsTitle: 'Daily albums',
    albumsIntro: 'Each diary moment becomes a small memory card with its own mood image.',
    backToDiary: 'Back to diary',
    emptyAlbums: 'Your albums will appear after you write your first moment.',
    moments: 'one daily sphere',
  },
  ru: {
    buddyName: 'Jey',
    diaryName: 'Дневник Jey',
    headline: 'Дневник, который отвечает.',
    intro:
      'Ребёнок может писать или записывать чувства, а потом сам решает, что останется личным, а что можно показать родителю.',
    mineMood: 'Это останется личным',
    moodMood: 'Можно показать только настроение',
    parentMood: 'Можно мягко поделиться',
    welcome:
      'Я Jey. Расскажи столько, сколько хочешь. Ты сам выбираешь, что останется только твоим.',
    placeholder: 'Напиши, что было сегодня, или запиши голос.',
    diaryLabel: 'Сообщение дневника',
    conversationLabel: 'Разговор с дневником',
    onlyMine: 'Только моё',
    moodOnly: 'Поделиться настроением',
    parentOk: 'Можно родителю',
    moodBadge: 'Настроение родителю',
    parentBadge: 'Можно родителю',
    aiTakeaway: 'Спросить Jey',
    aiTakeawayLoading: 'Jey читает день',
    aiTakeawayEmpty: 'Jey пока не смог сделать вывод.',
    me: 'Я',
    thinking: 'Jey думает',
    send: 'Отправить',
    record: 'Запись',
    stop: 'Стоп',
    voiceReady: 'Голосовая заметка готова',
    voiceTranscriptHint: 'Если слова не появились, напиши одну короткую фразу перед отправкой.',
    noRecording: 'В этом браузере запись недоступна.',
    micNeeded: 'Чтобы записать голос, нужен доступ к микрофону.',
    parentSignal: 'Сигнал родителю',
    noHint:
      'Сейчас сигнала для родителя нет. Личные записи остаются личными, пока ребёнок сам не решит иначе.',
    voiceEntry: 'Я сохранил голосовую заметку о своём дне.',
    albumsButton: 'Альбомы дня',
    registerButton: 'Регистрация',
    albumsTitle: 'Альбомы дня',
    albumsIntro: 'Каждый момент из дневника становится маленькой карточкой памяти.',
    backToDiary: 'Назад в дневник',
    emptyAlbums: 'Альбомы появятся после первой записи.',
    moments: 'одна сфера дня',
  },
  kk: {
    buddyName: 'Jey',
    diaryName: 'Jey күнделігі',
    headline: 'Жауап беретін күнделік.',
    intro:
      'Бала өз сезімін жазып немесе дауысымен сақтап, ненің жеке қалатынын, ненің ата-анаға көрсетілетінін өзі таңдайды.',
    mineMood: 'Бұл жеке болып қалады',
    moodMood: 'Тек көңіл күйді бөлісуге болады',
    parentMood: 'Жұмсақ бөлісуге болады',
    welcome:
      'Мен Jey. Қалағаныңша айт. Ненің тек өзіңдікі болатынын өзің таңдайсың.',
    placeholder: 'Бүгін не болғанын жаз немесе дауысыңды жазып ал.',
    diaryLabel: 'Күнделік хабарламасы',
    conversationLabel: 'Күнделік әңгімесі',
    onlyMine: 'Тек менікі',
    moodOnly: 'Көңіл күйді бөлісу',
    parentOk: 'Ата-анаға болады',
    moodBadge: 'Көңіл күй бөлісілді',
    parentBadge: 'Ата-анаға болады',
    aiTakeaway: 'Jey-ден сұрау',
    aiTakeawayLoading: 'Jey күнді оқып жатыр',
    aiTakeawayEmpty: 'Jey әзірге қорытынды жасай алмады.',
    me: 'Мен',
    thinking: 'Jey ойланып жатыр',
    send: 'Жіберу',
    record: 'Жазу',
    stop: 'Тоқтату',
    voiceReady: 'Дауыс жазбасы дайын',
    voiceTranscriptHint: 'Егер сөздер шықпаса, жіберер алдында бір қысқа жол жаз.',
    noRecording: 'Бұл браузерде дауыс жазу қолжетімсіз.',
    micNeeded: 'Дауыс жазу үшін микрофонға рұқсат керек.',
    parentSignal: 'Ата-анаға белгі',
    noHint:
      'Қазір ата-анаға белгі жоқ. Бала өзі шешпейінше жеке жазбалар жеке болып қалады.',
    voiceEntry: 'Мен бүгінгі күнім туралы дауыс жазбасын сақтадым.',
    albumsButton: 'Күн альбомдары',
    registerButton: 'Тіркелу',
    albumsTitle: 'Күн альбомдары',
    albumsIntro: 'Күнделіктегі әр сәт көңіл күй суреті бар естелікке айналады.',
    backToDiary: 'Күнделікке қайту',
    emptyAlbums: 'Алғашқы жазбадан кейін альбомдар осы жерде пайда болады.',
    moments: 'бір күн сферасы',
  },
};
